#Apache Tomcat icin server port ayarlamasi
server:
  port: 9090

  #hibernate icin ve JDBC baglantıları için configlei yaziyoruz.
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_jpa
    username: postgres
    password: 196969
  jpa:
    hibernate:
      ddl-auto: update
